# Generated by Django 2.2 on 2019-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittedlist',
            name='allowed',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.permittedlist'),
        ),
    ]
