# Generated by Django 2.2 on 2019-12-28 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20191217_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittedlist',
            name='allowed',
            field=models.ManyToManyField(to='accounts.permittedlist'),
        ),
        migrations.CreateModel(
            name='resolvedlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved', models.ManyToManyField(to='accounts.resolvedlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
